apiVersion: v1
kind: Pod
metadata:
  name: stress-test
spec:
  containers:
  - image: polinux/stress
    name: stress-test
    command: ["stress"]
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    args: ["--vm", "1", "--vm-bytes", "80M", "--timeout", "10s"]